spring.application.name=active
jwt.secret=Borboleta26
spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
spring.datasource.username=estrelas
spring.datasource.password=estrelas_aprendiz
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080
logging.level.org.springframework=INFO
spring.jpa.defer-datasource-initialization=true
